"""baseline sync all tables

Revision ID: 725b06848faf
Revises: 
Create Date: 2026-05-07 10:34:23.939926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725b06848faf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analysis_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ai_analysis_logs', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ai_analysis_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_ai_analysis_logs_id'), 'ai_analysis_logs', ['id'], unique=False)
    op.alter_column('ai_tasks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ai_tasks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('ai_tasks_task_id_key'), 'ai_tasks', type_='unique')
    op.drop_index(op.f('idx_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('idx_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('idx_ai_tasks_user_id'), table_name='ai_tasks')
    op.create_index(op.f('ix_ai_tasks_id'), 'ai_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=True)
    op.alter_column('community_posts', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('community_posts', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('community_posts', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('idx_community_posts_user_id'), table_name='community_posts')
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.drop_column('community_posts', 'comment_count')
    op.drop_column('community_posts', 'visibility')
    op.drop_column('community_posts', 'fork_count')
    op.drop_column('community_posts', 'tags')
    op.alter_column('food_record_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('food_record_items', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('food_record_items', 'calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_food_record_items_record_id'), table_name='food_record_items')
    op.create_index(op.f('ix_food_record_items_food_record_id'), 'food_record_items', ['food_record_id'], unique=False)
    op.create_index(op.f('ix_food_record_items_id'), 'food_record_items', ['id'], unique=False)
    op.alter_column('food_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('food_records', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('food_records', 'total_calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_food_records_record_time'), table_name='food_records')
    op.drop_index(op.f('idx_food_records_user_id'), table_name='food_records')
    op.drop_index(op.f('idx_food_records_user_time'), table_name='food_records')
    op.create_index(op.f('ix_food_records_id'), 'food_records', ['id'], unique=False)
    op.create_index(op.f('ix_food_records_record_time'), 'food_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_food_records_user_id'), 'food_records', ['user_id'], unique=False)
    op.alter_column('fridge_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fridge_items', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('fridge_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_fridge_items_expire_date'), table_name='fridge_items')
    op.drop_index(op.f('idx_fridge_items_user_id'), table_name='fridge_items')
    op.create_index(op.f('ix_fridge_items_expire_date'), 'fridge_items', ['expire_date'], unique=False)
    op.create_index(op.f('ix_fridge_items_id'), 'fridge_items', ['id'], unique=False)
    op.create_index(op.f('ix_fridge_items_user_id'), 'fridge_items', ['user_id'], unique=False)
    op.alter_column('health_feedbacks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('health_feedbacks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('health_feedbacks', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('health_feedbacks', 'bloating_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_health_feedbacks_food_record_id'), table_name='health_feedbacks')
    op.drop_index(op.f('idx_health_feedbacks_user_id'), table_name='health_feedbacks')
    op.create_index(op.f('ix_health_feedbacks_food_record_id'), 'health_feedbacks', ['food_record_id'], unique=False)
    op.create_index(op.f('ix_health_feedbacks_id'), 'health_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_health_feedbacks_user_id'), 'health_feedbacks', ['user_id'], unique=False)
    op.alter_column('post_comments', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('post_comments', 'post_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('post_comments', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_post_comments_post_id'), table_name='post_comments')
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.alter_column('post_forks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('post_forks', 'post_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('post_forks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('post_forks', 'target_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('post_forks', 'new_plan_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_post_forks_post_id'), table_name='post_forks')
    op.create_index(op.f('ix_post_forks_id'), 'post_forks', ['id'], unique=False)
    op.create_index(op.f('ix_post_forks_post_id'), 'post_forks', ['post_id'], unique=False)
    op.alter_column('post_likes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('post_likes', 'post_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('post_likes', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_post_likes_post_id'), table_name='post_likes')
    op.drop_constraint(op.f('uq_post_likes_post_user'), 'post_likes', type_='unique')
    op.create_index(op.f('ix_post_likes_id'), 'post_likes', ['id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.alter_column('recipe_recommendations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('recipe_recommendations', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_recipe_recommendations_id'), 'recipe_recommendations', ['id'], unique=False)
    op.alter_column('taste_vectors', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('taste_vectors', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_taste_vectors_id'), 'taste_vectors', ['id'], unique=False)
    op.alter_column('upload_files', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('upload_files', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('upload_files', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_upload_files_id'), 'upload_files', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'profile_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_upload_files_id'), table_name='upload_files')
    op.alter_column('upload_files', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('upload_files', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('upload_files', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_taste_vectors_id'), table_name='taste_vectors')
    op.alter_column('taste_vectors', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('taste_vectors', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_recipe_recommendations_id'), table_name='recipe_recommendations')
    op.alter_column('recipe_recommendations', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('recipe_recommendations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_id'), table_name='post_likes')
    op.create_unique_constraint(op.f('uq_post_likes_post_user'), 'post_likes', ['post_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.alter_column('post_likes', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_likes', 'post_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_likes', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_post_forks_post_id'), table_name='post_forks')
    op.drop_index(op.f('ix_post_forks_id'), table_name='post_forks')
    op.create_index(op.f('idx_post_forks_post_id'), 'post_forks', ['post_id'], unique=False)
    op.alter_column('post_forks', 'new_plan_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('post_forks', 'target_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('post_forks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_forks', 'post_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_forks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.create_index(op.f('idx_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.alter_column('post_comments', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_comments', 'post_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('post_comments', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_health_feedbacks_user_id'), table_name='health_feedbacks')
    op.drop_index(op.f('ix_health_feedbacks_id'), table_name='health_feedbacks')
    op.drop_index(op.f('ix_health_feedbacks_food_record_id'), table_name='health_feedbacks')
    op.create_index(op.f('idx_health_feedbacks_user_id'), 'health_feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('idx_health_feedbacks_food_record_id'), 'health_feedbacks', ['food_record_id'], unique=False)
    op.alter_column('health_feedbacks', 'fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'bloating_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('health_feedbacks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('health_feedbacks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_fridge_items_user_id'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_id'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_expire_date'), table_name='fridge_items')
    op.create_index(op.f('idx_fridge_items_user_id'), 'fridge_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_fridge_items_expire_date'), 'fridge_items', ['expire_date'], unique=False)
    op.alter_column('fridge_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('fridge_items', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('fridge_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_food_records_user_id'), table_name='food_records')
    op.drop_index(op.f('ix_food_records_record_time'), table_name='food_records')
    op.drop_index(op.f('ix_food_records_id'), table_name='food_records')
    op.create_index(op.f('idx_food_records_user_time'), 'food_records', ['user_id', 'record_time'], unique=False)
    op.create_index(op.f('idx_food_records_user_id'), 'food_records', ['user_id'], unique=False)
    op.create_index(op.f('idx_food_records_record_time'), 'food_records', ['record_time'], unique=False)
    op.alter_column('food_records', 'total_carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('food_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_food_record_items_id'), table_name='food_record_items')
    op.drop_index(op.f('ix_food_record_items_food_record_id'), table_name='food_record_items')
    op.create_index(op.f('idx_food_record_items_record_id'), 'food_record_items', ['food_record_id'], unique=False)
    op.alter_column('food_record_items', 'carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('food_record_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('community_posts', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('community_posts', sa.Column('fork_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('community_posts', sa.Column('visibility', sa.VARCHAR(length=30), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=True))
    op.add_column('community_posts', sa.Column('comment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.create_index(op.f('idx_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.alter_column('community_posts', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('community_posts', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('community_posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_id'), table_name='ai_tasks')
    op.create_index(op.f('idx_ai_tasks_user_id'), 'ai_tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=False)
    op.create_index(op.f('idx_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_unique_constraint(op.f('ai_tasks_task_id_key'), 'ai_tasks', ['task_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_tasks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_tasks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_ai_analysis_logs_id'), table_name='ai_analysis_logs')
    op.alter_column('ai_analysis_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('ai_analysis_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('ai_analysis_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
