"""align all models

Revision ID: a75590c2e74e
Revises: 
Create Date: 2026-05-07 00:45:07.761565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a75590c2e74e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_post_comments_post_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_table('ai_analysis_logs')
    op.drop_index(op.f('idx_post_forks_post_id'), table_name='post_forks')
    op.drop_table('post_forks')
    op.drop_index(op.f('idx_post_likes_post_id'), table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_table('taste_vectors')
    op.drop_table('recipe_recommendations')
    op.drop_table('upload_files')
    op.alter_column('ai_tasks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ai_tasks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('ai_tasks_task_id_key'), 'ai_tasks', type_='unique')
    op.drop_index(op.f('idx_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('idx_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('idx_ai_tasks_user_id'), table_name='ai_tasks')
    op.create_index(op.f('ix_ai_tasks_id'), 'ai_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=True)
    op.alter_column('community_posts', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('community_posts', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('community_posts', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('idx_community_posts_user_id'), table_name='community_posts')
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.drop_column('community_posts', 'visibility')
    op.drop_column('community_posts', 'tags')
    op.drop_column('community_posts', 'fork_count')
    op.drop_column('community_posts', 'comment_count')
    op.alter_column('food_record_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('food_record_items', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('food_record_items', 'calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_food_record_items_record_id'), table_name='food_record_items')
    op.create_index(op.f('ix_food_record_items_food_record_id'), 'food_record_items', ['food_record_id'], unique=False)
    op.create_index(op.f('ix_food_record_items_id'), 'food_record_items', ['id'], unique=False)
    op.alter_column('food_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('food_records', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('food_records', 'total_calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_food_records_record_time'), table_name='food_records')
    op.drop_index(op.f('idx_food_records_user_id'), table_name='food_records')
    op.drop_index(op.f('idx_food_records_user_time'), table_name='food_records')
    op.create_index(op.f('ix_food_records_id'), 'food_records', ['id'], unique=False)
    op.create_index(op.f('ix_food_records_record_time'), 'food_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_food_records_user_id'), 'food_records', ['user_id'], unique=False)
    op.alter_column('fridge_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fridge_items', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('fridge_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_fridge_items_expire_date'), table_name='fridge_items')
    op.drop_index(op.f('idx_fridge_items_user_id'), table_name='fridge_items')
    op.create_index(op.f('ix_fridge_items_expire_date'), 'fridge_items', ['expire_date'], unique=False)
    op.create_index(op.f('ix_fridge_items_id'), 'fridge_items', ['id'], unique=False)
    op.create_index(op.f('ix_fridge_items_user_id'), 'fridge_items', ['user_id'], unique=False)
    op.alter_column('health_feedbacks', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('health_feedbacks', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('health_feedbacks', 'food_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('health_feedbacks', 'bloating_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_health_feedbacks_food_record_id'), table_name='health_feedbacks')
    op.drop_index(op.f('idx_health_feedbacks_user_id'), table_name='health_feedbacks')
    op.create_index(op.f('ix_health_feedbacks_food_record_id'), 'health_feedbacks', ['food_record_id'], unique=False)
    op.create_index(op.f('ix_health_feedbacks_id'), 'health_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_health_feedbacks_user_id'), 'health_feedbacks', ['user_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'profile_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_health_feedbacks_user_id'), table_name='health_feedbacks')
    op.drop_index(op.f('ix_health_feedbacks_id'), table_name='health_feedbacks')
    op.drop_index(op.f('ix_health_feedbacks_food_record_id'), table_name='health_feedbacks')
    op.create_index(op.f('idx_health_feedbacks_user_id'), 'health_feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('idx_health_feedbacks_food_record_id'), 'health_feedbacks', ['food_record_id'], unique=False)
    op.alter_column('health_feedbacks', 'fatigue_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'bloating_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('health_feedbacks', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('health_feedbacks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('health_feedbacks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_fridge_items_user_id'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_id'), table_name='fridge_items')
    op.drop_index(op.f('ix_fridge_items_expire_date'), table_name='fridge_items')
    op.create_index(op.f('idx_fridge_items_user_id'), 'fridge_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_fridge_items_expire_date'), 'fridge_items', ['expire_date'], unique=False)
    op.alter_column('fridge_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('fridge_items', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('fridge_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_food_records_user_id'), table_name='food_records')
    op.drop_index(op.f('ix_food_records_record_time'), table_name='food_records')
    op.drop_index(op.f('ix_food_records_id'), table_name='food_records')
    op.create_index(op.f('idx_food_records_user_time'), 'food_records', ['user_id', 'record_time'], unique=False)
    op.create_index(op.f('idx_food_records_user_id'), 'food_records', ['user_id'], unique=False)
    op.create_index(op.f('idx_food_records_record_time'), 'food_records', ['record_time'], unique=False)
    op.alter_column('food_records', 'total_carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'total_calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_records', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('food_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_food_record_items_id'), table_name='food_record_items')
    op.drop_index(op.f('ix_food_record_items_food_record_id'), table_name='food_record_items')
    op.create_index(op.f('idx_food_record_items_record_id'), 'food_record_items', ['food_record_id'], unique=False)
    op.alter_column('food_record_items', 'carbohydrate_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'fat_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'protein_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'calories',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('food_record_items', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('food_record_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('community_posts', sa.Column('comment_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('community_posts', sa.Column('fork_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('community_posts', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('community_posts', sa.Column('visibility', sa.VARCHAR(length=30), server_default=sa.text("'public'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.create_index(op.f('idx_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.alter_column('community_posts', 'food_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('community_posts', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('community_posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_id'), table_name='ai_tasks')
    op.create_index(op.f('idx_ai_tasks_user_id'), 'ai_tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=False)
    op.create_index(op.f('idx_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_unique_constraint(op.f('ai_tasks_task_id_key'), 'ai_tasks', ['task_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_tasks', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('ai_tasks', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('upload_files',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('scene', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('upload_files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('upload_files_pkey'))
    )
    op.create_table('recipe_recommendations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recipe_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('steps_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('nutrition_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recipe_recommendations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recipe_recommendations_pkey'))
    )
    op.create_table('taste_vectors',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('vector_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('updated_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('taste_vectors_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('taste_vectors_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('taste_vectors_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('post_likes',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('post_likes_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_likes_pkey')),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('uq_post_likes_post_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_table('post_forks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_meal_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('new_plan_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('post_forks_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_forks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_forks_pkey'))
    )
    op.create_index(op.f('idx_post_forks_post_id'), 'post_forks', ['post_id'], unique=False)
    op.create_table('ai_analysis_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prompt_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_analysis_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analysis_logs_pkey'))
    )
    op.create_table('post_comments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('post_comments_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('post_comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('post_comments_pkey'))
    )
    op.create_index(op.f('idx_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    # ### end Alembic commands ###
